pages/urls.py
"""Django page CMS urls module."""

from django.conf.urls.defaults import url, include, patterns
from django.conf.urls.defaults import handler404, handler500
from pages.views import details
from pages import settings

if settings.PAGE_USE_LANGUAGE_PREFIX:
    urlpatterns = patterns('',
        url(r'^(?P<lang>[-\w]+)/(?P<path>.*)$', details,
            name='pages-details-by-path'),
        # can be used to change the URL of the root page
        #url(r'^$', details, name='pages-root'),
    )
else:
    urlpatterns = patterns('',
        url(r'^(?P<path>.*)$', details, name='pages-details-by-path'),
        # can be used to change the URL of the root page
        #url(r'^$', details, name='pages-root'),
    )

pages/admin/forms.py
# -*- coding: utf-8 -*-
"""Page CMS forms"""
from django import forms
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _

from pages import settings
from pages.models import Page, Content
from pages.urlconf_registry import get_choices
from pages.widgets import LanguageChoiceWidget

# error messages
another_page_error = _('Another page with this slug already exists')
sibling_position_error = _('A sibling with this slug already exists at the \
targeted position')
child_error = _('A child with this slug already exists at the targeted \
position')
sibling_error = _('A sibling with this slug already exists')
sibling_root_error = _('A sibling with this slug already exists at the root \
level')

class PageForm(forms.ModelForm):
    """Form for page creation"""

    title = forms.CharField(
        label=_('Title'),
        widget=forms.TextInput(),
    )
    slug = forms.CharField(
        label=_('Slug'),
        widget=forms.TextInput(),
        help_text=_('The slug will be used to create the page URL, \
it must be unique among the other pages of the same level.')
    )
    language = forms.ChoiceField(
        label=_('Language'),
        choices=settings.PAGE_LANGUAGES,
        widget=LanguageChoiceWidget()
    )
    template = forms.ChoiceField(
        required=False,
        label=_('Template'),
        choices=settings.get_page_templates(),
    )
    delegate_to = forms.ChoiceField(
        required=False,
        label=_('Delegate to application'),
        choices=get_choices(),
    )
    freeze_date = forms.DateTimeField(
        required=False,
        label=_('Freeze'),
        help_text=_("Don't publish any content after this date. Format is 'Y-m-d H:M:S'")
        # those make tests fail miserably
        #widget=widgets.AdminSplitDateTime()
        #widget=widgets.AdminTimeWidget()
    )

    target = forms.IntegerField(required=False, widget=forms.HiddenInput)
    position = forms.CharField(required=False, widget=forms.HiddenInput)

    class Meta:
        model = Page

    def clean_slug(self):
        """Handle move action on the pages"""

        slug = slugify(self.cleaned_data['slug'])
        target = self.data.get('target', None)
        position = self.data.get('position', None)

        if settings.PAGE_UNIQUE_SLUG_REQUIRED:
            if self.instance.id:
                if Content.objects.exclude(page=self.instance).filter(
                    body=slug, type="slug").count():
                    raise forms.ValidationError(another_page_error)
            elif Content.objects.filter(body=slug, type="slug").count():
                raise forms.ValidationError(another_page_error)

        if settings.PAGE_USE_SITE_ID:
            if settings.PAGE_HIDE_SITES:
                site_ids = [settings.SITE_ID]
            else:
                site_ids = [int(x) for x in self.data.getlist('sites')]
            def intersects_sites(sibling):
                return sibling.sites.filter(id__in=site_ids).count() > 0
        else:
            def intersects_sites(sibling):
                return True

        if not settings.PAGE_UNIQUE_SLUG_REQUIRED:
            if target and position:
                target = Page.objects.get(pk=target)
                if position in ['right', 'left']:
                    slugs = [sibling.slug() for sibling in
                             target.get_siblings()
                             if intersects_sites(sibling)]
                    slugs.append(target.slug())
                    if slug in slugs:
                        raise forms.ValidationError(sibling_position_error)
                if position == 'first-child':
                    if slug in [sibling.slug() for sibling in
                                target.get_children()
                                if intersects_sites(sibling)]:
                        raise forms.ValidationError(child_error)
            else:
                if self.instance.id:
                    if (slug in [sibling.slug() for sibling in
                        self.instance.get_siblings().exclude(
                            id=self.instance.id
                        ) if intersects_sites(sibling)]):
                        raise forms.ValidationError(sibling_error)
                else:
                    if slug in [sibling.slug() for sibling in
                                Page.objects.root()
                                if intersects_sites(sibling)]:
                        raise forms.ValidationError(sibling_root_error)
        return slug

pages/templates/pages/widgets/autocompletetaginput.html
<script type="text/javascript">
<!--
    jQuery("#id_{{ name }}").autocomplete({{ tags|safe }}, {
        width: 150,
        max: 10,
        highlight: false,
        multiple: true,
        multipleSeparator: ", ",
        scroll: true,
        scrollHeight: 300,
        matchContains: true,
        autoFill: true,
    });
-->
</script>

pages/templates/pages/widgets/ckeditor.html
<script type="text/javascript">
<!--
    CKEDITOR.replace( 'id_{{name}}', {
        toolbar : [
            [      'Undo', 'Redo',
              '-', 'Bold', 'Italic', 'Underline',
              '-', 'Image',
              '-', 'Link', 'Unlink', 'Anchor',
              '-', 'Format',
              '-', 'SpellChecker', 'Scayt',
              '-', 'Maximize'
            ],
            [      'HorizontalRule',
              '-', 'Table',
              '-', 'BulletedList', 'NumberedList',
              '-', 'Cut','Copy','Paste','PasteText','PasteFromWord',
              '-', 'SpecialChar',
              '-', 'Source',
              '-', 'About'
            ]
        ],
        uiColor : '#CCC',
        width : 640,
        height : 400
    });
    
    {% if filebrowser %}
        CKEDITOR.config.filebrowserBrowseUrl = '/admin/filebrowser/browse/?pop=3';
    {% endif %}
-->
</script>

pages/templates/pages/widgets/editarea.html
<script type="text/javascript">
editAreaLoader.init({
	id : "id_{{ name }}"		// textarea id
	,syntax: "html"			// syntax to be uses for highgliting
	,start_highlight: true		// to display with highlight mode on start-up
    ,font_family: "verdana, monospace"
    ,allow_resize: "n"
    ,min_width:  800
    ,min_height: 300
    ,toolbar: "search, go_to_line, |, undo, redo, |, select_font,|, change_smooth_selection, highlight, reset_highlight, word_wrap, |, help"
});
</script>

pages/templates/pages/widgets/languages.html
{% load i18n pages_tags %}

<input id="id_language" name="language" type="hidden" value="{{ value }}" />

<ul class="clearfix">
{% for lang in page_languages %}
    {% ifequal value lang.0 %}
        <li><span class="current">{{ lang.0 }}</span></li>
    {% else %}
        {% if page|has_content_in:lang.0 %}
            <li><a class="editlink" href="?language={{ lang.0 }}">{{ lang.0 }}</a></li>
        {% else %}
            <li><a class="addlink" href="?language={{ lang.0 }}">{{ lang.0 }}</a></li>
        {% endif %}
    {% endifequal %}
{% endfor %}
</ul>
{% if page|has_content_in:value %}
<p style="clear:both"><a class="deletelink js-confirm-delete" href="/admin/pages/page/{{
page.id }}/delete-content/{{ language }}/">{% trans "Delete this translation" %}</a></p>
{% endif %}

pages/templates/pages/widgets/markituphtml.html
<script type="text/javascript">
<!--
    // mySettings is defined in markitup/sets/default/set.js
    $('#id_{{ name }}').markItUp(mySettings);
-->
</script>

pages/templates/pages/widgets/markitupmarkdown.html
<script type="text/javascript">
<!--
    // mySettings is defined in markitup/sets/markdown/set.js
    $('#id_{{ name }}').markItUp(mySettings);
-->
</script>

pages/templates/pages/widgets/markituprest.html
<script type="text/javascript">
<!--
    // mySettings is defined in markitup/sets/rst/set.js
    $('#id_{{ name }}').markItUp(mySettings);
-->
</script>

pages/templates/pages/widgets/richtextarea.html
<script type="text/javascript">
<!--
    if(window.$) {
        $(document).ready(function() {
            if($.fn.rte)
                $('#id_{{ name }}').rte('{{ PAGES_MEDIA_URL }}/css/rte.css', '{{ PAGES_MEDIA_URL }}images/rte/');
        });
    }
-->
</script>

pages/templates/pages/widgets/tinymce.html
<script type="text/javascript">
$(function(){
    tinyMCE.init({
        mode : "exact",
        elements : "id_{{name}}",
        language: "{{ language }}",
        width : "640px",
        height: "400px",
        theme : "advanced",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left"
    });
});
</script>

pages/templates/pages/widgets/wymeditor.html
{% load mptt_tags pages_tags %}
<script type="text/javascript">
<!--
    jQuery('#id_{{ name }}').wymeditor({
        langPath: "{{ PAGES_MEDIA_URL }}wymeditor/lang/",
        lang: '{{ lang }}',
        skin: 'django',
        skinPath: "{{ PAGES_MEDIA_URL }}javascript/wymeditor/skins/django/",
        updateSelector: 'form',
        updateEvent: 'submit',
        containersItems: [
            {'name': 'P', 'title': 'Paragraph', 'css': 'wym_containers_p'},
            {'name': 'H3', 'title': 'Heading_3', 'css': 'wym_containers_h3'},
            {'name': 'H4', 'title': 'Heading_4', 'css': 'wym_containers_h4'},
            {'name': 'H5', 'title': 'Heading_5', 'css': 'wym_containers_h5'}
        ],
        classesItems: [
            {'name': 'left', 'title': 'Image left align', 'expr': 'img'},
            {'name': 'right', 'title': 'Image right align', 'expr': 'img'},
            {'name': 'border', 'title': 'Image border', 'expr': 'img'},
            {'name': 'external', 'title': 'External link', 'expr': 'a'}
        ],
        
        editorStyles: [
            {'name': 'img', 'css': 'margin: 0 0 1.5em; max-width: 100%;'},
            {'name': 'p img', 'css': 'float: left; margin: 0.7em 0 0.8em 0; position: relative; width: 98%;'},
            {'name': 'p img.left', 'css': 'float: left; margin: 0.7em 1em 0.8em 0; width: auto;'},
            {'name': 'p img.right', 'css': 'float: right; margin: 0.7em 0 0.8em 1em; width: auto;'},
            
            {'name': 'img', 'css': 'border: none;'},
            {'name': 'img.border', 'css': 'border: 2px solid #757575;'}
        ],
        
        postInit: function(wym) {
            if ({{ page_link_wymeditor }}) {
                //construct the button's html
                html = "<li class='wym_tools_pagelink'>"
                     + "<a name='PageLink' href='#'"
                     + " title='Page link'"
                     + " style='background-image:"
                     + " url({{ PAGES_MEDIA_URL }}javascript/wymeditor/skins/django/icons.png);"
                     + " background-position: 0 -623px;'>"
                     + "Page link"
                     + "</a></li>";

                //add the button to the tools box
                jQuery(wym._box)
                .find(wym._options.toolsSelector + wym._options.toolsListSelector)
                .append(html);

                //handle click event on wrap button
                jQuery(wym._box)
                .find('li.wym_tools_pagelink a').click(function() {
                    var selected_page_id = 0;
                    // get Selection
                    var sel = wym.selected();
                    if (sel != null){
                        if (sel.tagName.toLowerCase() == 'a') {
                            // do we have a selection?
                            if (sel.className != null){
                                var page_id = sel.className.split('_'); 
                                var selected_page_id = page_id[1];
                            }
                        }
                    }
                    //construct the dialog's html
                    html = "<body class='wym_dialog wym_dialog_pagelink'"
                         + " onload='WYMeditor.INIT_DIALOG(" + WYMeditor.INDEX + ");jQuery(\".wym_select_pagelink option.page_" 
                         + selected_page_id + "\").attr(\"selected\",\"selected\").addClass(\"selected\");'"
                         + ">"
                         + "<form>"
                         + "<fieldset>"
                         + "<input type='hidden' class='wym_dialog_type' value='"
                         + "Pages"
                         + "' />"
                         + "<legend>Page link {{ lang }}</legend>"
                         + "<div class='row'>"
                         + "<label>Page</label>"
                         + "<select class='wym_select_pagelink'>"
                         {% for page in page_list %}
                         + "<option class='page_{{page.id}}' value='{% show_absolute_url page language %}#{{page.id}}'>{% show_slug_with_level page language %}</option>"
                         {% endfor %}
                         + "</select>"
                         + "</div>"
                         + "<div class='row row-indent'>"
                         + "<input class='wym_submit wym_submit_pagelink' type='button'"
                         + " value='{Submit}' />"
                         + "<input class='wym_cancel' type='button'"
                         + "value='{Cancel}' />"
                         + "</div>"
                         + "</fieldset>"
                         + "</form>"
                         + "</body>";

                    wym.dialog("Link Page", "menubar=no,titlebar=no,toolbar=no,resizable=no"
                               + ",width=560,height=200,top=0,left=0", html);
                
                    return(false);
                });
            }           
            wym.resizable({handles: "s", maxHeight: 600});


        },
        //handle click event on dialog's submit button
        postInitDialog: function( wym, wdw ) {
            if ({{ page_link_wymeditor }}) {
                var body = wdw.document.body;
                jQuery(body)
                    .find('input.wym_submit_pagelink')
                    .click(function() {
                        var values = jQuery(body).find('.wym_select_pagelink').val().split('#');
                        wym.wrap('<a class="page_' + values[1] + '" href="' + values[0] + '" title="">', '</a>');
                        wdw.close();
    
                    });
            }
            if ({{ filebrowser }}) {
                // Filebrowser callback
                wymeditor_filebrowser(wym, wdw);
            }
        }
    });
-->
</script>